"""Title-block layout measurement. ONE definition, shared by G10 and verify_pdf.

Why this file exists
--------------------
The title-block spacing bounced four times: 0.9em -> 2.2em -> 3.6em, each
tuned by eye and each still wrong when Havid read the page. The fourth
measurement found the actual cause: `\\vspace` placed after `\\end{minipage}`
lands in horizontal mode, so LaTeX DISCARDED it. The source asked for 3.6em
and the rendered gap was 0.11 pt.

Three blind tunings failed because nobody measured the artifact. So the gap is
now measured in points on the rendered page, and the numbers below bracket the
layout Havid accepted rather than being typed in as an aesthetic guess.

Shared between `s18d` (gate G10) and `scripts/verify_pdf.py` deliberately: a
guard applied in only one consumer diverges, which is exactly how the
narration filter let a leak through G4 (handbook 7.6 #10). Measurement code is
no different from filter code in that respect.
"""
from __future__ import annotations

import pathlib

# Bands bracket the MEASURED and ACCEPTED August 2026 v4 layout:
#     author     -> affiliation 1   14.42 pt
#     affiliation-> date            22.52 pt
#     date       -> Abstract        23.74 pt
#     Abstract   -> body            10.17 pt
# Havid's requirement was "date not too close to the affiliation, Abstract not
# too far from the date", i.e. the two middle gaps should be comparable. They
# are within 1.3 pt of each other. Bands allow normal font-metric drift while
# failing the collapse (0.11 pt) and the over-shoot (68.54 pt) that shipped.
BANDS = {
    "author_to_affil": (8.0, 24.0),
    "affil_to_date": (14.0, 34.0),
    "date_to_abstract": (14.0, 40.0),
    "abstract_to_body": (5.0, 20.0),
}

# The two middle gaps must not diverge wildly, which is the balance complaint
# in Havid's own words rather than an absolute size.
MAX_MIDDLE_RATIO = 2.5

# Corresponding-author marker (Havid, 2026-09-09). The asterisk on the author
# line and the note explaining it are GENERATED by s18d, so nothing asserted
# they were still there. A future refactor of the title block could silently
# drop either one and every existing gate would still report pass: G10 measures
# GAPS between anchors, and losing the note only shifts a gap by a couple of
# points, well inside the bands.
#
# That is the 0.2 pattern -- a defect class becomes an assertion, not a prompt
# reminder -- and it is measured on the RENDERED page rather than the source,
# because markdown inspection has missed every format defect this project has
# shipped (0.3).
#
# Both halves are required, and that pairing is the actual contract: an
# asterisk with no note is an unexplained marker, and a note with no asterisk
# marks nobody. The email must be the one in config/author_manifest / the
# boilerplate module; a title page that prints a different address than the
# submission metadata is the drift this catches.
CORRESP_EMAIL = "havidaqoma.khoiruddin@xmu.edu.my"


def _lines(page) -> list[tuple[float, float, str]]:
    out = []
    for blk in page.get_text("dict")["blocks"]:
        for ln in blk.get("lines", []):
            txt = "".join(s["text"] for s in ln["spans"]).strip()
            if txt:
                out.append((min(s["bbox"][1] for s in ln["spans"]),
                            max(s["bbox"][3] for s in ln["spans"]), txt))
    out.sort()
    return out


def measure(pdf_path: str | pathlib.Path, author: str = "Havid Aqoma",
            date_str: str | None = None) -> dict:
    """Return the four title-block gaps in points, measured on page 1.

    `date_str` is passed by the build so the check does not have to guess the
    date format. verify_pdf omits it and falls back to a month-name scan.
    """
    import pymupdf

    with pymupdf.open(str(pdf_path)) as doc:
        rows = _lines(doc[0])
        page_count = doc.page_count

    def find(pred):
        return next((r for r in rows if pred(r[2])), None)

    author_ln = find(lambda t: author.split()[0] in t and author.split()[-1] in t)
    affil1 = find(lambda t: t.lstrip().startswith("1"))
    if date_str:
        date_ln = find(lambda t: date_str in t)
    else:
        MONTHS = ("January February March April May June July August "
                  "September October November December").split()
        date_ln = find(lambda t: any(t.strip().startswith(m) for m in MONTHS)
                       and "," in t and len(t) < 30)
    abstract = find(lambda t: t.strip() == "Abstract")
    body = None
    if abstract:
        body = next((r for r in rows if r[0] > abstract[1] + 0.5), None)

    # The last affiliation is the last line above the date.
    last_affil = None
    if date_ln:
        cands = [r for r in rows if r[1] <= date_ln[0] + 0.5
                 and r is not date_ln]
        last_affil = cands[-1] if cands else None

    gaps: dict[str, float | None] = {}

    def gap(name, a, b):
        gaps[name] = round(b[0] - a[1], 2) if (a and b) else None

    gap("author_to_affil", author_ln, affil1)
    gap("affil_to_date", last_affil, date_ln)
    gap("date_to_abstract", date_ln, abstract)
    gap("abstract_to_body", abstract, body)

    failures = []
    for name, (lo, hi) in BANDS.items():
        v = gaps.get(name)
        if v is None:
            failures.append(f"{name}: could not locate both anchors")
        elif not (lo <= v <= hi):
            failures.append(f"{name}: {v} pt outside [{lo}, {hi}]")

    mid = [gaps.get("affil_to_date"), gaps.get("date_to_abstract")]
    ratio = None
    if all(isinstance(x, float) and x > 0 for x in mid):
        ratio = round(max(mid) / min(mid), 2)
        if ratio > MAX_MIDDLE_RATIO:
            failures.append(
                f"affil->date and date->abstract differ by {ratio}x "
                f"(max {MAX_MIDDLE_RATIO}); the block reads unbalanced")

    # ---- corresponding-author marker, measured on the rendered page -------
    # Read from the page text rather than the source, for the reason in the
    # CORRESP_EMAIL comment above. `author_ln` is the author line as it
    # RENDERED, so the asterisk check sees what a reader sees: pymupdf gives
    # "Havid Aqoma1,2,3,4,*" because the superscript is just text in a span.
    corresp = {"asterisk_on_author": False, "note_present": False,
               "email_present": False, "email": CORRESP_EMAIL,
               "note_below_affiliations": False, "note_line": None}
    if author_ln:
        corresp["asterisk_on_author"] = "*" in author_ln[2]
    note_ln = find(lambda t: "orresponding author" in t)
    if note_ln:
        corresp["note_present"] = True
        corresp["note_line"] = note_ln[2][:120]
        corresp["email_present"] = CORRESP_EMAIL in note_ln[2]
        # Havid asked for the note "somewhere below the affiliation list", so
        # position is part of the requirement, not just presence.
        if affil1:
            corresp["note_below_affiliations"] = note_ln[0] > affil1[0]
    else:
        # The email may still be on the page without the marker sentence.
        corresp["email_present"] = any(CORRESP_EMAIL in r[2] for r in rows)

    if not corresp["asterisk_on_author"]:
        failures.append("corresponding-author asterisk missing from the "
                        "author line")
    if not corresp["note_present"]:
        failures.append("the note explaining the * is missing; an unexplained "
                        "marker is worse than none")
    if not corresp["email_present"]:
        failures.append(f"corresponding-author email {CORRESP_EMAIL} not on "
                        f"the title page")
    if corresp["note_present"] and not corresp["note_below_affiliations"]:
        failures.append("the corresponding-author note is not below the "
                        "affiliation list")

    # G5 hardcodes title_block_fraction = 0.40. Derive it instead: the title
    # block is everything above the Abstract heading, as a fraction of the
    # text height. A hardcoded layout constant is a latent 7.3 bug.
    tb_fraction = None
    if abstract and rows:
        top = rows[0][0]
        tb_fraction = round((abstract[0] - top) / 720.0, 3)

    return {"gaps_pt": gaps, "bands": {k: list(v) for k, v in BANDS.items()},
            "middle_ratio": ratio, "max_middle_ratio": MAX_MIDDLE_RATIO,
            "title_block_fraction_measured": tb_fraction,
            "page_count": page_count,
            "status": "pass" if not failures else "fail",
            "failures": failures}
